import argparse
import json
import os
from typing import Any, Dict, Optional
from urllib.parse import urlparse

from epic4.config import config
from epic4.storage_client import StorageClient
from epic4.summary import generate_summary_artifacts
from epic4.utils import logger


class SummaryRunError(Exception):
    """Raised when a summary run cannot complete successfully."""


def _load_doc_snapshot(snapshot_path: str) -> Dict[str, Any]:
    if not os.path.exists(snapshot_path):
        raise FileNotFoundError(f"doc_snapshot.json is required at {snapshot_path}")

    with open(snapshot_path, "r") as f:
        snapshot = json.load(f)

    if not isinstance(snapshot, dict):
        raise ValueError("doc_snapshot.json must contain a JSON object")

    return snapshot


def _derive_runtime_values(
    snapshot: Dict[str, Any],
    commit_override: str,
    summary_bucket_path_override: str = "",
) -> Dict[str, str]:
    docs_bucket_path = snapshot.get("docs_bucket_path")
    if not docs_bucket_path:
        raise ValueError("docs_bucket_path is required in doc_snapshot.json")

    docs_bucket_path = str(docs_bucket_path)
    if not docs_bucket_path.endswith("/"):
        docs_bucket_path += "/"

    project_id = str(snapshot.get("project_id", ""))
    commit_hash = str(snapshot.get("commit") or commit_override or "").strip()
    if not commit_hash:
        raise ValueError("commit is required in message payload, CLI args, or doc_snapshot.json")

    if summary_bucket_path_override:
        summary_bucket_path = summary_bucket_path_override
    else:
        summary_bucket_path = docs_bucket_path + "summary/"

    summary_bucket_path = str(summary_bucket_path)
    if summary_bucket_path.startswith(("az://", "azure://", "s3://", "gs://", "r2://")):
        parsed = urlparse(summary_bucket_path)
        key_path = parsed.path.lstrip("/")
        if not key_path:
            raise ValueError("summary_bucket_path URI must include a non-empty path")
        summary_bucket_uri = summary_bucket_path
        summary_bucket_path = key_path
    else:
        if not summary_bucket_path.endswith("/"):
            summary_bucket_path += "/"
        summary_bucket_uri = f"r2://{config.R2_BUCKET_NAME}/{summary_bucket_path}"

    return {
        "project_id": project_id,
        "commit_hash": commit_hash,
        "docs_bucket_path": docs_bucket_path,
        "summary_bucket_path": summary_bucket_path,
        "summary_bucket_uri": summary_bucket_uri,
    }


def run_summary_pipeline(
    impact_path: str,
    drift_path: str,
    commit_sha: str = "",
    output_dir: Optional[str] = None,
    snapshot_path: Optional[str] = None,
    storage_client: Optional[StorageClient] = None,
    summary_bucket_path_override: str = "",
) -> Dict[str, Any]:
    effective_snapshot_path = snapshot_path or config.DOC_SNAPSHOT_PATH
    effective_output_dir = output_dir or config.SUMMARIES_DIR

    snapshot = _load_doc_snapshot(effective_snapshot_path)
    runtime = _derive_runtime_values(snapshot, commit_sha, summary_bucket_path_override)

    commit_hash = runtime["commit_hash"]
    summary_bucket_uri = runtime["summary_bucket_uri"]

    logger.info(f"Starting Epic-4 execution for commit {commit_hash} in mode SUMMARY_ONLY_MODE")

    summary_md_path = ""
    summary_json_path = ""
    try:
        summary_md_path, summary_json_path = generate_summary_artifacts(
            impact_path,
            drift_path,
            commit_hash,
            effective_output_dir,
            snapshot,
        )
        logger.info(f"Summary generated successfully at {summary_md_path}")
    except Exception as e:
        logger.error(f"Failed to generate summary: {e}")
        summary_md_path = os.path.join(effective_output_dir, "summary.md")
        summary_json_path = os.path.join(effective_output_dir, "summary.json")
        os.makedirs(effective_output_dir, exist_ok=True)

        summary_content = f"""# Change Summary - Generation Failed

**Commit SHA:** `{commit_hash}`
**Status:** ERROR

## Error
Summary generation encountered an error:
```
{str(e)}
```

This is a degraded artifact. Please check the impact and drift reports manually.

---
*Generated by Epic-4 Automation*
"""

        with open(summary_md_path, "w") as f:
            f.write(summary_content)

        with open(summary_json_path, "w") as f:
            json.dump({"error": str(e), "status": "ERROR", "commit_sha": commit_hash}, f)

        logger.info(f"Created error summary at {summary_md_path}")

    storage = storage_client or StorageClient()
    logger.info(f"Uploading summary artifacts to {summary_bucket_uri}")
    upload_success_md = storage.upload_file(summary_md_path, summary_bucket_uri)
    upload_success_json = storage.upload_file(summary_json_path, summary_bucket_uri)

    if not (upload_success_md and upload_success_json):
        raise SummaryRunError("Summary upload failed")

    logger.info("Summary artifacts uploaded successfully")

    return {
        "status": "success",
        "project_id": runtime["project_id"],
        "commit": commit_hash,
        "summary_bucket_path": runtime["summary_bucket_path"],
        "generated_files": ["summary.md", "summary.json"],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Epic-4 CI Automation")
    parser.add_argument("--impact", default=config.IMPACT_REPORT_PATH, help="Path to impact report")
    parser.add_argument("--drift", default=config.DRIFT_REPORT_PATH, help="Path to drift report")
    parser.add_argument("--commit", default=config.COMMIT_SHA, help="Commit SHA override")
    parser.add_argument("--snapshot", default=config.DOC_SNAPSHOT_PATH, help="Path to doc_snapshot.json")
    parser.add_argument("--output-dir", default=config.SUMMARIES_DIR, help="Path to generated summaries")
    parser.add_argument(
        "--summary-bucket-path",
        default="",
        help="Optional override for summary path (relative path or full URI)",
    )

    args = parser.parse_args()

    response = run_summary_pipeline(
        impact_path=args.impact,
        drift_path=args.drift,
        commit_sha=args.commit,
        output_dir=args.output_dir,
        snapshot_path=args.snapshot,
        summary_bucket_path_override=args.summary_bucket_path,
    )
    print(json.dumps(response))


if __name__ == "__main__":
    main()
